-- cspell: disable
return {
  { -- Useful plugin to show you pending keybinds.
    'folke/which-key.nvim',
    event = 'VimEnter',
    opts = {
      delay = 0,
      icons = {
        mappings = vim.g.have_nerd_font,
        keys = vim.g.have_nerd_font and {} or {
          Up = '<Up> ',
          Down = '<Down> ',
          Left = '<Left> ',
          Right = '<Right> ',
          C = '<C-…> ',
          M = '<M-…> ',
          D = '<D-…> ',
          S = '<S-…> ',
          CR = '<CR> ',
          Esc = '<Esc> ',
          ScrollWheelDown = '<ScrollWheelDown> ',
          ScrollWheelUp = '<ScrollWheelUp> ',
          NL = '<NL> ',
          BS = '<BS> ',
          Space = '<Space> ',
          Tab = '<Tab> ',
          F1 = '<F1>',
          F2 = '<F2>',
          F3 = '<F3>',
          F4 = '<F4>',
          F5 = '<F5>',
          F6 = '<F6>',
          F7 = '<F7>',
          F8 = '<F8>',
          F9 = '<F9>',
          F10 = '<F10>',
          F11 = '<F11>',
          F12 = '<F12>',
        },
      },
      spec = {
        { '<leader>c', group = '[C]ode', mode = { 'n', 'x' } },
        { '<leader>d', group = '[D]ocument' },
        { '<leader>r', group = '[R]ename' },
        { '<leader>s', group = '[S]earch' },
        { '<leader>w', group = '[W]orkspace' },
        { '<leader>t', group = '[T]oggle' },
        { '<leader>b', group = '[B]uffer' },
        { '<leader>h', group = 'Git [H]unk', mode = { 'n', 'v' } },
        { '<leader>v', group = '[V]env' },
        { '<leader>dd', group = '[D]elete' },
        { '<leader>dy', group = '[Y]ank' },
        { '<leader>cf', group = '[F]ormat' },
        { 'gs', group = '[S]urround' },
        { 'gl', desc = 'Toggle line comment', mode = 'n' },
        { 'gR', desc = 'LSP References', mode = 'n' },
        { 'gan', desc = 'Around Next', mode = { 'n', 'x', 'o' } },
        { 'gal', desc = 'Around Last', mode = { 'n', 'x', 'o' } },
        { 'gin', desc = 'Inside Next', mode = { 'n', 'x', 'o' } },
        { 'gil', desc = 'Inside Last', mode = { 'n', 'x', 'o' } },
        { '<leader>ci', desc = 'cspell: ignore word', mode = 'n' },
        { '<leader>cw', desc = 'cspell: add word', mode = 'n' },
        { '<leader>cs', desc = 'cspell: use suggestion', mode = 'n' },
      },
    },
  },
}
